version: '3.2'

services:
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    networks:
      - app-network
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - $PWD/data/grafana:/var/lib/grafana
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    networks:
      - app-network
  merc-benz-route-checker:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    expose: 
      - 8080
    networks:
      - app-network
    depends_on:
      - elk
      - graphite
networks:
  app-network:
    driver: bridge