version: '3.2'

services:
  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
        - "discovery.type=single-node"
    ports:
        - 9200:9200
        - 9300:9300
    networks:
        - elknetwork
  kibana:
    image: kibana:7.7.0
    container_name: kibana
    hostname: kibana
    ports:
        - 5601:5601
    links:
        - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elknetwork
  logstash:
    image: logstash:7.7.0
    container_name: logstash
    hostname: logstash
    ports:
        - 9600:9600
        - 8089:8089
    volumes:
      - ./logstash:/usr/share/logstash/pipeline/
    links:
        - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elknetwork
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - $PWD/data/grafana:/var/lib/grafana
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    networks:
      - app-network
  merc-benz-route-checker:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        mode: ${mode}
    ports:
      - 8080:8080
    expose: 
      - 8080
    networks:
      - app-network
    depends_on:
      - logstash
      - graphite
networks:
  app-network:
    driver: bridge
  elknetwork:
    driver: bridge