{
 "title": "merc-benz-route-checker",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Vin",
    "query": "stats_counts.counters.computetravel.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of users",
   "type": "stat",
   "description": "Provides the unique number of users/cars using this application",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "countSeries(unique(stats.timers.*.computetravel.count))"
    }
   ]
  },
  {
   "title": "External API response time",
   "type": "timeseries",
   "description": "Provides the average time taken to retrieve charge level, travel distance and charging stations data from respective APIs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(stats.timers.api.chargelevel.upper_90, 'Charge Level API')"
    },
    {
     "target": "alias(stats.timers.api.traveldistance.upper_90, 'Travel Distance API')"
    },
    {
     "target": "alias(stats.timers.api.chargestation.upper_90, 'Charge Station API')"
    }
   ]
  },
  {
   "title": "API response time",
   "type": "timeseries",
   "description": "Provides the average time taken by /compute-route api from the time of getting the request till the time of returning the response. Metric is specific to user. Filterable by Vin.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(stats.timers.$Vin.computetravel.upper_90, 'Response Time')"
    }
   ]
  },
  {
   "title": "Algorithm computation time",
   "type": "timeseries",
   "description": "Shows the time elapsed for the core algorithm of the microservice to compute list of stations that needs to be visited for charging.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(sumSeries(stats.timers.*.computetravel.computeroute.upper_90), 'Algorithm Computation time')"
    }
   ]
  },
  {
   "title": "Request stats",
   "type": "timeseries",
   "description": "Counts number of success and failure operations during the API request.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "target": "alias(nonNegativeDerivative(transformNull(sumSeries(stats_counts.counters.computetravel.*.success), 0)), 'Success')"
    },
    {
     "target": "alias(nonNegativeDerivative(transformNull(sumSeries(stats_counts.counters.computetravel.*.failure), 0)), 'Failure')"
    },
    {
     "target": "alias(nonNegativeDerivative(transformNull(sumSeries(stats_counts.counters.computetravel.*.nocharge), 0)), 'No Charge')"
    },
    {
     "target": "alias(nonNegativeDerivative(transformNull(sumSeries(stats_counts.counters.computetravel.*.sufficientfuel), 0)), 'Sufficient Fuel')"
    }
   ]
  }
 ]
}